import{initializeApp}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import{getDatabase,ref,get,set,push,onValue,update}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js";

// IMPORTANT: copy the firebaseConfig object from your currently-working AuctionXI app.js here.
const firebaseConfig = {
  apiKey: "AIzaSyCL556A_syoypvLv8w6S951LdnMsuqAxUc",
  authDomain: "auctionxi-7f389.firebaseapp.com",
  databaseURL: "https://auctionxi-7f389-default-rtdb.asia-southeast1.firebasedatabase.app",
  projectId: "auctionxi-7f389",
  storageBucket: "auctionxi-7f389.firebasestorage.app",
  messagingSenderId: "173927110591",
  appId: "1:173927110591:web:c26f96c9516e1a9296730a",
  measurementId: "G-SG22FQD9TF"
};const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app);const $=id=>document.getElementById(id);const show=(id,v)=>$(id)?.classList.toggle("hidden",!v);const msg=(id,t)=>{if($(id))$(id).textContent=t||""};
let settings={tournamentName:"AuctionXI Tournament",totalPoints:1200,playersRequired:8,minBid:30};let players={};let filter="all";
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function maxBid(remaining,bought){const need=Math.max(0,settings.playersRequired-(bought+1));return Math.max(0,remaining-need*settings.minBid)}
function renderSettings(){if($("tName"))$("tName").value=settings.tournamentName||"";if($("points"))$("points").value=settings.totalPoints;if($("required"))$("required").value=settings.playersRequired;if($("minBid"))$("minBid").value=settings.minBid;if($("startMax"))$("startMax").textContent=Math.max(0,settings.totalPoints-settings.playersRequired*settings.minBid);if($("adminTitle"))$("adminTitle").textContent=settings.tournamentName||"AuctionXI Tournament")}
async function login(){const e=$("email")?.value.trim(),p=$("password")?.value;if(!e||!p)return msg("loginMsg","Please enter both email and password.");const b=$("loginBtn");b.disabled=true;b.textContent="Signing in…";try{await signInWithEmailAndPassword(auth,e,p)}catch(x){console.error(x);msg("loginMsg",x.code==="auth/invalid-credential"?"Login failed: email or password is incorrect.":"Login failed: "+(x.code||x.message))}finally{b.disabled=false;b.textContent="Sign in"}}
async function saveSettings(){const total=Number($("points").value),req=Number($("required").value),min=Number($("minBid").value),name=$("tName").value.trim()||"AuctionXI Tournament";if(!Number.isFinite(total)||!Number.isFinite(req)||!Number.isFinite(min)||total<req*min||req<1||min<0)return msg("saveMsg","Enter valid settings. Total points must cover all minimum bids.");try{await set(ref(db,"tournaments/main/settings"),{tournamentName:name,totalPoints:total,playersRequired:req,minBid:min});msg("saveMsg","Settings saved.")}catch(e){msg("saveMsg","Could not save: "+e.message)}}
function statusBadge(s){return `<span class="badge ${s}">${esc(s.toUpperCase())}</span>`}
function renderPlayers(){const list=$("playerList"),pool=$("auctionPool");if(!list)return;const arr=Object.entries(players).map(([id,p])=>({id,...p})).filter(p=>filter==="all"||p.status===filter).sort((a,b)=>String(a.playerId).localeCompare(String(b.playerId)));list.innerHTML=arr.length?arr.map(p=>`<div class="player"><img src="${esc(p.photo)}" alt="Player photo"><div><b>${esc(p.name)}</b><br><small>${esc(p.playerId)} · ${esc(p.city)} · CricHeroes: ${esc(p.cricheroes)}</small><br>${statusBadge(p.status)} ${p.previous?`<small>Previous: ${esc(p.previous)}</small>`:""}</div><div class="actions">${p.status!=="approved"?`<button type="button" data-act="approve" data-id="${p.id}" class="secondary">Approve</button>`:""}${p.status!=="rejected"?`<button type="button" data-act="reject" data-id="${p.id}" class="secondary">Reject</button>`:""}${p.status==="approved"?`<button type="button" data-act="auction" data-id="${p.id}" class="secondary">${p.selected?"Remove from auction":"Add to auction"}</button>`:""}</div></div>`).join(""):`<p class="note">No players in this view.</p>`;if(pool){const a=Object.entries(players).map(([id,p])=>({id,...p})).filter(p=>p.status==="approved");pool.innerHTML=a.length?a.map(p=>`<div class="player"><img src="${esc(p.photo)}" alt=""><div><b>${esc(p.name)}</b><br><small>${esc(p.playerId)} · ${esc(p.city)}</small><br>${p.selected?statusBadge("approved"):"<span class='badge pending'>NOT SELECTED</span>"}</div><div><button type="button" class="secondary" data-act="auction" data-id="${p.id}">${p.selected?"Remove":"Select"}</button></div></div>`).join(""):`<p class="note">Approve players first.</p>`}}
async function playerAction(id,act){const p=players[id];if(!p)return;const patch={};if(act==="approve")patch.status="approved";if(act==="reject")patch.status="rejected";if(act==="auction")patch.selected=!p.selected;if(Object.keys(patch).length)await update(ref(db,"tournaments/main/players/"+id),patch)}
function nextPlayerId(){let max=0;Object.values(players).forEach(p=>{const n=Number(String(p.playerId||"").replace("AXI-",""));if(Number.isFinite(n))max=Math.max(max,n)});return`AXI-${String(max+1).padStart(4,"0")}`}
function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=600,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext("2d").drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL("image/jpeg",.72))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
async function addPlayer(e){e.preventDefault();const f=$("pPhoto").files[0],name=$("pName").value.trim(),city=$("pCity").value.trim(),cr=$("pCricheroes").value.trim();if(!f||!name||!city||!cr)return msg("playerMsg","Please complete every required field.");try{msg("playerMsg","Processing photo…");const photo=await compress(f),id=push(ref(db,"tournaments/main/players")).key;await set(ref(db,"tournaments/main/players/"+id),{playerId:nextPlayerId(),name,city,cricheroes:cr,previous:$("pPrevious").value.trim(),photo,status:"pending",selected:false,createdAt:Date.now()});$("playerForm").reset();$("photoPreview").textContent="No photo selected";msg("playerMsg","Player added to the approval queue.")}catch(x){console.error(x);msg("playerMsg","Could not add player: "+x.message)}}
async function handleUser(u){if(!u){show("login",true);show("admin",false);show("team",false);show("logout",false);return}show("login",false);show("logout",true);try{const s=await get(ref(db,"users/"+u.uid));if(!s.exists())throw Error("No AuctionXI role assigned.");const p=s.val();if(p.role==="admin"){show("admin",true);show("team",false);startAdmin()}else if(p.role==="team"){show("team",true);show("admin",false);startTeam(p)}else throw Error("Unknown AuctionXI role.")}catch(e){console.error(e);msg("loginMsg","AuctionXI error: "+e.message);await signOut(auth).catch(()=>{});show("login",true);show("logout",false)}}
function startAdmin(){onValue(ref(db,"tournaments/main/settings"),s=>{if(s.exists())settings={...settings,...s.val()};renderSettings()});onValue(ref(db,"tournaments/main/players"),s=>{players=s.exists()?s.val():{};renderPlayers()});onValue(ref(db,"tournaments/main/teams"),s=>{const el=$("teams");if(!el)return;el.innerHTML=s.exists()?Object.values(s.val()).map(t=>`<div class="box"><b>${esc(t.name||"Unnamed")}</b><br><small>${esc(t.email||"")}</small></div>`).join(""):"<p class='note'>No teams yet.</p>"});renderSettings()}
function startTeam(p){onValue(ref(db,"tournaments/main/settings"),s=>{if(s.exists())settings={...settings,...s.val()}});onValue(ref(db,"tournaments/main/teams/"+p.teamId),s=>{if(!s.exists())return;const t=s.val(),b=Number(t.bought||0),r=Number(t.remaining??settings.totalPoints);$("teamNameOut").textContent=t.name||"Team";$("teamTournament").textContent=settings.tournamentName;$("remaining").textContent=r;$("bought").textContent=`${b} / ${settings.playersRequired}`;$("maxBid").textContent=maxBid(r,b);$("reserve").textContent=Math.max(0,settings.playersRequired-b)*settings.minBid})}
$("loginBtn")?.addEventListener("click",login);$("password")?.addEventListener("keydown",e=>{if(e.key==="Enter")login()});$("logout")?.addEventListener("click",()=>signOut(auth));$("save")?.addEventListener("click",saveSettings);$("playerForm")?.addEventListener("submit",addPlayer);$("pPhoto")?.addEventListener("change",async()=>{const f=$("pPhoto").files[0];if(!f)return;try{$("photoPreview").innerHTML=`<img src="${esc(await compress(f))}" alt="Preview">`}catch{msg("playerMsg","Could not preview photo.")}});document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tabpane").forEach(x=>x.classList.add("hidden"));b.classList.add("active");$("tab-"+b.dataset.tab).classList.remove("hidden")}));document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.status;renderPlayers()}));document.addEventListener("click",e=>{const b=e.target.closest("button[data-act]");if(b)playerAction(b.dataset.id,b.dataset.act).catch(x=>console.error(x))});$("selectAll")?.addEventListener("click",async()=>{const updates={};Object.entries(players).forEach(([id,p])=>{if(p.status==="approved")updates[`${id}/selected`]=true});if(Object.keys(updates).length)await update(ref(db,"tournaments/main/players"),updates)});onAuthStateChanged(auth,handleUser);renderSettings();
