import{initializeApp}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import{getDatabase,ref,get,set,onValue}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js";

/* Replace only this config with the config from your NEW AuctionXI Firebase Web App. */
const firebaseConfig={apiKey:"PASTE_API_KEY",authDomain:"PASTE_PROJECT.firebaseapp.com",databaseURL:"PASTE_DATABASE_URL",projectId:"PASTE_PROJECT_ID",storageBucket:"PASTE_STORAGE_BUCKET",messagingSenderId:"PASTE_SENDER_ID",appId:"PASTE_APP_ID",measurementId:"PASTE_MEASUREMENT_ID"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app);
const $=id=>document.getElementById(id), show=(id,v)=>$(id).classList.toggle("hidden",!v);
let settings={tournamentName:"AuctionXI Tournament",totalPoints:1200,playersRequired:8,minBid:30};

function maxBid(remaining,bought){const need=Math.max(0,settings.playersRequired-(bought+1));return bought===0?Math.max(0,settings.totalPoints-settings.playersRequired*settings.minBid):Math.max(0,remaining-need*settings.minBid)}
function renderSettings(){ $("tName").value=settings.tournamentName||"";$("points").value=settings.totalPoints;$("required").value=settings.playersRequired;$("minBid").value=settings.minBid;$("startMax").textContent=Math.max(0,settings.totalPoints-settings.playersRequired*settings.minBid);$("sName").textContent=settings.tournamentName||"—";$("sPoints").textContent=settings.totalPoints;$("sReq").textContent=settings.playersRequired}
function adminListeners(){onValue(ref(db,"tournaments/main/settings"),s=>{if(s.exists())settings={...settings,...s.val()};renderSettings()});onValue(ref(db,"tournaments/main/teams"),s=>{const el=$("teams");el.innerHTML="";if(!s.exists()){el.innerHTML="<p class='note'>No teams yet.</p>";return}Object.values(s.val()).forEach(t=>{const d=document.createElement("div");d.innerHTML="<b>"+(t.name||"Unnamed team")+"</b><br><small>"+(t.email||"")+"</small>";el.appendChild(d)})})}
$("loginBtn").onclick=async()=>{try{await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value)}catch(e){$("loginMsg").textContent=e.message}};
$("logout").onclick=()=>signOut(auth);
$("save").onclick=async()=>{const total=+$("points").value,req=+$("required").value,min=+$("minBid").value;if(total<req*min){$("saveMsg").textContent="Total points must be at least "+req*min;return}await set(ref(db,"tournaments/main/settings"),{tournamentName:$("tName").value.trim()||"AuctionXI Tournament",totalPoints:total,playersRequired:req,minBid:min});$("saveMsg").textContent="Settings saved."};
onAuthStateChanged(auth,async u=>{if(!u){show("login",true);show("admin",false);show("team",false);show("logout",false);return}show("login",false);show("logout",true);const s=await get(ref(db,"users/"+u.uid));if(!s.exists()){alert("This account is not assigned an AuctionXI role.");await signOut(auth);return}const p=s.val();if(p.role==="admin"){show("admin",true);show("team",false);adminListeners()}else if(p.role==="team"){show("team",true);show("admin",false);onValue(ref(db,"tournaments/main/settings"),x=>{if(x.exists())settings={...settings,...x.val()};});onValue(ref(db,"tournaments/main/teams/"+p.teamId),x=>{if(!x.exists())return;const t=x.val(),b=+(t.bought||0),r=+(t.remaining??settings.totalPoints);$("teamNameOut").textContent=t.name||"Team";$("teamTournament").textContent=settings.tournamentName;$("remaining").textContent=r;$("bought").textContent=b+" / "+settings.playersRequired;$("maxBid").textContent=maxBid(r,b);$("reserve").textContent=Math.max(0,settings.playersRequired-b)*settings.minBid})}});
